version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: "mysql"
    restart: "no"
    ports:
      - 3310:3306
    volumes:
      - ./source/data:/var/lib/mysql
    networks:
      - mysql_normalnet

networks:
  mysql_normalnet:

