version: '3.8'

services:
  mysql_source:
    image: mysql:8.0
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=ROW --innodb_flush_log_at_trx_commit=1 --sync_binlog=1
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: "mysql_source"
    restart: "no"
    ports:
      - 3307:3306
    volumes:
      - ./source/data:/var/lib/mysql
    networks:
      - mysql_replinet

  mysql_replica1:
    image: mysql:8.0
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=ROW --innodb_flush_log_at_trx_commit=1 --sync_binlog=1
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: "mysql_replica1"
    restart: "no"
    ports:
      - 3308:3306
    depends_on:
      - mysql_source
    volumes:
      - ./replica1/data:/var/lib/mysql
    networks:
      - mysql_replinet

  mysql_replica2:
    image: mysql:8.0
    command: --server-id=3 --log-bin=mysql-bin --binlog-format=ROW --innodb_flush_log_at_trx_commit=1 --sync_binlog=1
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: "mysql_replica2"
    restart: "no"
    ports:
      - 3309:3306
    depends_on:
      - mysql_source
    volumes:
      - ./replica2/data:/var/lib/mysql
    networks:
      - mysql_replinet

networks:
  mysql_replinet:

